### ISSUE TITLE
Avoid exploring the correct PWM sign and retrieve this info from the API

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/study-improve-head-edpr#5]
Hi @davidetome 

I've seen that you explore the movement direction in PWM mode as per below:

https://github.com/icub-tech-iit/study-improve-head-edpr/blob/81e90c74d663af9a5bccf81e78f5af55a1d9a258/log-joint/src/main.cpp#L187-L201

Actually, it'd be better to retrieve this info from the API as done for example in:

https://github.com/robotology/icub-main/blob/master/src/libraries/ctrlLib/src/tuning.cpp#L291-L293.

**Comment by davidetome** [comment]
I modified the [code](https://github.com/davidetome/study-improve-head-edpr/blob/60e59490705d714977c0ddcd0a05ac2b1e6ddbb7/log-joint/src/main.cpp#L202) retrieving the PID gain sign from the API.
Tested this morning on the purple only on the pan because of the tilt, in PWM mode, has a strange behaviour


https://user-images.githubusercontent.com/6638215/128502075-1265b46f-77bc-425f-872d-ebf29b0f67e7.mp4


cc @pattacini

**Comment by pattacini** [comment]
Ok! This is exactly the weird behavior reported by EDPR. Essentially, the motor is not capable enough of delivering the required power.

Did you already push the mods to the repo?
It'd be great to collect a further set of acquisitions to investigate the way the PWM control mode now works.

**Comment by pattacini** [comment]
BTW, I think you can close this issue.

**Comment by davidetome** [comment]
> Did you already push the mods to the repo?

at the moment pushed on my [fork](https://github.com/davidetome/study-improve-head-edpr/blob/60e59490705d714977c0ddcd0a05ac2b1e6ddbb7/log-joint/src/main.cpp#L202)

> It'd be great to collect a further set of acquisitions to investigate the way the PWM control mode now works.

This morning I hadn't the time to change the pwm acquisition behaviour in order to avoid lack of that during the pause
