### ISSUE TITLE
Review the way we control the joint in PWM

### ISSUE THREAD

**Issue by pattacini** [icub-tech-iit/study-improve-head-edpr#6]
After #5 is done, we should revise and fix the strategy we adopt to control the joint in PWM for logging purposes.

**Comment by davidetome** [comment]
Today, using iCubGenova09, I modified the [code](https://github.com/davidetome/study-improve-head-edpr/commit/863f98b5950ea1c5549a14b775bd8faa490ba8ad) and :

- Tested the PWM/PID sign retrieve from the API also on joint 3 on `iCubGenova09`
- Modified the code in order to log data also during the pause when the setpoint is reached; 

[j3-pos.log](https://github.com/icub-tech-iit/study-improve-head-edpr/files/6982115/j3-pos.log)
[j3-pwm.log](https://github.com/icub-tech-iit/study-improve-head-edpr/files/6982116/j3-pwm.log)
[j4-pos.log](https://github.com/icub-tech-iit/study-improve-head-edpr/files/6982117/j4-pos.log)
[j4-pwm.log](https://github.com/icub-tech-iit/study-improve-head-edpr/files/6982118/j4-pwm.log)

@pattacini , I'm going to do some cleanup and check why this [piece of code](https://github.com/davidetome/study-improve-head-edpr/blob/863f98b5950ea1c5549a14b775bd8faa490ba8ad/log-joint/src/main.cpp#L126) causes seg fault; then I'll open the PR

**Comment by pattacini** [comment]
Hi @davidetome 

The following PWM commands are not really correct.

![image](https://user-images.githubusercontent.com/3738070/129354326-ef6dba70-a914-4544-9252-a718e22a047f.png)

We should command in PWM with a pure square wave, that is without the PWM = 0 zones.

**Comment by davidetome** [comment]
@pattacini  the PWM is set to 0 during the pause otherwise the joint keeps moving right? I should remove the pause when the joint is reached?

**Comment by pattacini** [comment]
>@pattacini the PWM is set to 0 during the pause otherwise the joint keeps moving right? I should remove the pause when the joint is reached?

When you reach the setpoint you just need to change the sign of the PWM, this will allow us to avoid setting PWM = 0.
We will thus obtain a pure square wave, although the width of the wave will be slightly variable.

**Comment by davidetome** [comment]
ok, fixed

![gnome-shell-screenshot-V9KA80](https://user-images.githubusercontent.com/6638215/129361365-276486f2-00ec-4e88-9558-53ffe29ba78d.png)

[j3-pwm.log](https://github.com/icub-tech-iit/study-improve-head-edpr/files/6982626/j3-pwm.log)

**Comment by pattacini** [comment]
Sweet 🎉

**Comment by davidetome** [comment]
Done w/ this [PR](https://github.com/icub-tech-iit/study-improve-head-edpr/pull/7)
